Apply suggestions from code review

diff --git a/.github/workflows/go-tests.yml b/.github/workflows/go-tests.yml
--- a/.github/workflows/go-tests.yml
+++ b/.github/workflows/go-tests.yml
@@ -3,12 +3,25 @@ on: [push]
 jobs:
   test:
     name: Test
+    needs:
+      - get-go-version
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - name: Determine Go version
+        id: get-go-version
+        # We use .go-version as our source of truth for current Go
+        # version, because "goenv" can react to it automatically.
+        run: |
+          if [[ ! -f .go-version ]]; then
+            echo "::error::File not found: .go-version"
+            exit 1
+          fi
+          echo "Building with Go $(cat .go-version)"
+          echo "::set-output name=go-version::$(cat .go-version)"
       - uses: actions/setup-go@v3
         with:
-          go-version: '1.16'
+          go-version: ${{ steps.get-go-version.outputs.go-version }}
 
       # Get values for cache paths to be used in later steps
       - id: go-cache-paths
